baseURL: "https://yangkeunyun.github.io/" 
title: Yangkeun Yun
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: Job-market paper
          url: /research/navigating_the_commons/JMP_navigating_the_commons.pdf
          weight: 1
        - name: CV
          url: /cv-yangkeun-yun.pdf
          weight: 2
        - name: Research
          url: /research/
          weight: 3

params:
    description: "I am a PhD student in Economics at the UCLA Anderson School of Management."
    author: Yangkeun Yun
    googleAnalyticsID: "G-D54BS9DFQ6"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Yangkeun Yun
          subtitle: "Hello and thank you for visiting my page. I am a PhD candidate in economics at UCLA Anderson. My research fields are industrial organization, environmental economics, and economic history. I will be on the job market during the 2025–26 academic year."
          imageUrl: "/yun_yangkeun.jpeg"
          imageWidth: 230
          imageHeight: 230
          imageTitle: 
          buttons:
            - name: Job-market paper
              url: /research/navigating_the_commons/JMP_navigating_the_commons.pdf
            - name: CV
              url: "/cv-yangkeun-yun.pdf"   
            - name: Research
              url: /research/
    socialIcons:
        - name: Email
          url: mailto:yangkeun.yun.phd@anderson.ucla.edu
        - name: GitHub
          url: https://github.com/yangkeunyun

    assets:
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Yangkeun Yun"
      icon: /favicon-whale.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2

